# Generated by Django 3.0.2 on 2020-01-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200104_0219'),
        ('orders', '0003_auto_20200104_0218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders_Products',
            new_name='OrdersProducts',
        ),
        migrations.AlterField(
            model_name='ordersproducts',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
