# Generated by Django 3.0.2 on 2020-01-05 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200105_1844'),
        ('opinions', '0004_auto_20200105_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='product_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
