# Generated by Django 3.0.2 on 2020-01-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('nr_nip', models.PositiveIntegerField()),
                ('description', models.TextField(verbose_name=45)),
            ],
        ),
    ]
