# Generated by Django 3.0.2 on 2020-01-04 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='producent',
        ),
    ]
