# Generated by Django 3.0.2 on 2020-01-04 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_delete_producent'),
    ]

    operations = [
        migrations.CreateModel(
            name='producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('nr_nip', models.PositiveIntegerField()),
                ('description', models.TextField(verbose_name=45)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='producer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.producer'),
        ),
    ]
