# Generated by Django 3.0.2 on 2020-01-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200105_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='producer_id',
        ),
    ]
