# Generated by Django 3.0.2 on 2020-01-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_remove_product_producer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ex_date',
            field=models.DateTimeField(),
        ),
    ]
