# Generated by Django 3.0.2 on 2020-01-05 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20200105_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='producer_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Producer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producer',
            name='description',
            field=models.TextField(),
        ),
    ]
